added danish translation
DanielBiegler/pannellum-translation pull request #29
Opened 2017-10-01 13:15 UTC by GeorgThomassen

Closes [#10](https://github.com/DanielBiegler/pannellum-translation/issues/10)

2017-10-01 15:19 UTC, DanielBiegler requested changes
there is no "DA" ISO code.

denmark == "DK" !

2017-10-01 17:08 UTC, GeorgThomassen commented
Woops! Fixed that

2017-10-01 17:40 UTC, DanielBiegler approved these changes

2017-10-30 09:27 UTC, merged

2017-10-30 09:27 UTC, DanielBiegler commented
Thanks!